# Generated by Django 2.0.5 on 2018-05-19 16:01

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='attendRecord',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False, verbose_name='考勤记录编号')),
                ('attendStartTime', models.DateTimeField(blank=True, null=True, verbose_name='签到时间')),
                ('attendEndTime', models.DateTimeField(blank=True, null=True, verbose_name='签出时间')),
            ],
            options={
                'verbose_name': '考勤记录表',
                'verbose_name_plural': '考勤记录表',
                'db_table': 'attendrecord',
            },
        ),
        migrations.CreateModel(
            name='attendStatusInfo',
            fields=[
                ('attendStatusId', models.AutoField(primary_key=True, serialize=False, verbose_name='出勤状态编号')),
                ('attendStatus', models.CharField(max_length=200, verbose_name='出勤状态')),
            ],
            options={
                'verbose_name': '出勤状态表',
                'verbose_name_plural': '出勤状态表',
                'db_table': 'attendstatusinfo',
            },
        ),
        migrations.CreateModel(
            name='departmentInfo',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False, verbose_name='部门编号')),
                ('departmentName', models.CharField(max_length=200, verbose_name='部门名称')),
                ('departmentManager', models.CharField(max_length=200, verbose_name='部门经理')),
            ],
            options={
                'verbose_name': '部门信息表',
                'verbose_name_plural': '部门信息表',
                'db_table': 'departmentinfo',
            },
        ),
        migrations.CreateModel(
            name='employeeInfo',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False, verbose_name='员工编号')),
                ('employeeName', models.CharField(max_length=200, verbose_name='员工姓名')),
                ('age', models.CharField(blank=True, max_length=2, null=True, verbose_name='年龄')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True, verbose_name='联系方式')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='邮箱')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='地址')),
                ('jobStatus', models.CharField(max_length=20, null=True, verbose_name='目前状态')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.departmentInfo', verbose_name='部门编号')),
            ],
            options={
                'verbose_name': '员工信息表',
                'verbose_name_plural': '员工信息表',
                'db_table': 'employeeinfo',
            },
        ),
        migrations.CreateModel(
            name='jobNameInfo',
            fields=[
                ('jobNameId', models.AutoField(primary_key=True, serialize=False, verbose_name='职位编号')),
                ('jobName', models.CharField(max_length=200, verbose_name='职位名称')),
            ],
            options={
                'verbose_name': '职位信息表',
                'verbose_name_plural': '职位信息表',
                'db_table': 'jobnameinfo',
            },
        ),
        migrations.CreateModel(
            name='leaveInfo',
            fields=[
                ('leaveInfoId', models.AutoField(primary_key=True, serialize=False, verbose_name='请假编号')),
                ('leaveReason', models.TextField(verbose_name='请假原因')),
                ('leaveTotalDays', models.IntegerField(default=1, verbose_name='请假天数')),
                ('leaveTime', models.DateTimeField(verbose_name='请假时间')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.departmentInfo', verbose_name='部门编号')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo', verbose_name='员工编号')),
            ],
            options={
                'verbose_name': '请假记录表',
                'verbose_name_plural': '请假记录表',
                'db_table': 'leaveinfo',
            },
        ),
        migrations.CreateModel(
            name='paymentInfo',
            fields=[
                ('paymentInfoId', models.AutoField(primary_key=True, serialize=False, verbose_name='工资记录编号')),
                ('attendRecordInfo', models.CharField(max_length=200, verbose_name='出勤记录信息')),
                ('payment', models.CharField(max_length=200, verbose_name='发放工资')),
                ('createTime', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo', verbose_name='员工编号')),
            ],
            options={
                'verbose_name': '工资记录表',
                'verbose_name_plural': '工资记录表',
                'db_table': 'paymentinfo',
            },
        ),
        migrations.CreateModel(
            name='roleInfo',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False, verbose_name='角色编号')),
                ('roleName', models.CharField(max_length=200, verbose_name='角色名称')),
            ],
            options={
                'verbose_name': '角色信息表',
                'verbose_name_plural': '角色信息表',
                'db_table': 'roleinfo',
            },
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='jobNameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.jobNameInfo', verbose_name='职位编号'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.roleInfo', verbose_name='角色编号'),
        ),
        migrations.AddField(
            model_name='attendrecord',
            name='attendanceStatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.attendStatusInfo', verbose_name='出勤状态'),
        ),
        migrations.AddField(
            model_name='attendrecord',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo', verbose_name='员工编号'),
        ),
    ]
