# Generated by Django 2.0.5 on 2018-05-17 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roleInfo',
            fields=[
                ('roleId', models.AutoField(primary_key=True, serialize=False)),
                ('roleName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'roleinfo',
            },
        ),
    ]
