# Generated by Django 2.0.5 on 2018-05-17 12:54

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='attendRecord',
            fields=[
                ('attendanceId', models.AutoField(primary_key=True, serialize=False)),
                ('attendStartTime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('attendEndTime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'db_table': 'attendrecord',
            },
        ),
        migrations.CreateModel(
            name='attendStatusInfo',
            fields=[
                ('attendStatusId', models.AutoField(primary_key=True, serialize=False)),
                ('attendStatus', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'attendstatusinfo',
            },
        ),
        migrations.CreateModel(
            name='departmentInfo',
            fields=[
                ('departmentId', models.AutoField(primary_key=True, serialize=False)),
                ('departmentName', models.CharField(max_length=200)),
                ('departmentManager', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'departmentinfo',
            },
        ),
        migrations.CreateModel(
            name='employeeInfo',
            fields=[
                ('employeeId', models.AutoField(primary_key=True, serialize=False)),
                ('employeeName', models.CharField(max_length=200)),
                ('age', models.CharField(blank=True, max_length=2, null=True)),
                ('password', models.CharField(max_length=20)),
                ('phoneNumber', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('jobStatus', models.CharField(max_length=20)),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.departmentInfo')),
            ],
            options={
                'db_table': 'employeeinfo',
            },
        ),
        migrations.CreateModel(
            name='jobNameInfo',
            fields=[
                ('jobNameId', models.AutoField(primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'jobnameinfo',
            },
        ),
        migrations.CreateModel(
            name='leaveInfo',
            fields=[
                ('leaveInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('leaveReason', models.TextField()),
                ('leaveTime', models.DateTimeField()),
                ('createTime', models.DateTimeField()),
                ('departmentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.departmentInfo')),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo')),
            ],
            options={
                'db_table': 'leaveinfo',
            },
        ),
        migrations.CreateModel(
            name='paymentInfo',
            fields=[
                ('paymentInfoId', models.AutoField(primary_key=True, serialize=False)),
                ('attendRecordInfo', models.CharField(max_length=200)),
                ('payment', models.CharField(max_length=200)),
                ('createTime', models.DateTimeField(default=datetime.datetime.now)),
                ('employeeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo')),
            ],
            options={
                'db_table': 'paymentinfo',
            },
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='jobNameId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.jobNameInfo'),
        ),
        migrations.AddField(
            model_name='employeeinfo',
            name='roleId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.roleInfo'),
        ),
        migrations.AddField(
            model_name='attendrecord',
            name='attendanceStatusId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.attendStatusInfo'),
        ),
        migrations.AddField(
            model_name='attendrecord',
            name='employeeId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hrmanager.employeeInfo'),
        ),
    ]
