# Generated by Django 2.0.5 on 2018-05-26 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveinfo',
            name='leaveStatus1',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='hrmanager.confirmInfo', verbose_name='审批情况'),
        ),
    ]
