# Generated by Django 2.0.5 on 2018-05-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='age',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='leaveinfo',
            name='leaveTime',
            field=models.CharField(max_length=200, verbose_name='请假时间'),
        ),
    ]
