# Generated by Django 2.0.5 on 2018-05-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0002_auto_20180517_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendrecord',
            name='attendEndTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendrecord',
            name='attendStartTime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
