# Generated by Django 2.0.5 on 2018-05-21 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0002_auto_20180521_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveinfo',
            name='departmentId',
        ),
    ]
