# Generated by Django 2.0.5 on 2018-05-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrmanager', '0003_remove_leaveinfo_departmentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveinfo',
            name='leaveStatus',
            field=models.IntegerField(default=0, verbose_name='审批状态'),
        ),
    ]
